export const products = [
		{
			"id": 2,
			"image": "https://images.stockx.com/360/Nike-Air-Force-1-Low-Supreme-Box-Logo-White/Images/Nike-Air-Force-1-Low-Supreme-Box-Logo-White/Lv2/img01.jpg?fm=avif&auto=compress&w=480&dpr=3&updated_at=1635187755&h=320&q=50",
			"product": "NIKE AIR FORCE 1 - Supreme White",
			"description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
            "category": "tenis",
			"price": 91,
			"stock": 2,
		},
		{
            "id": 1,
			"image": "https://images.stockx.com/360/Nike-Air-Force-1-Low-Flax-2019/Images/Nike-Air-Force-1-Low-Flax-2019/Lv2/img01.jpg?fm=avif&auto=compress&w=480&dpr=3&updated_at=1635252806&h=320&q=50",
			"product": "NIKE AIR FORCE 1 - Flax (2019/2022)			",
			"description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
            "category": "tenis",
			"price": 110,
			"stock": 100,
		},
		{
            "id": 3,
			"image": "https://images.stockx.com/360/Nike-Air-Force-1-Low-Supreme-Box-Logo-Black/Images/Nike-Air-Force-1-Low-Supreme-Box-Logo-Black/Lv2/img01.jpg?fm=avif&auto=compress&w=480&dpr=2&updated_at=1635277631&h=320&q=75",
            "category": "tenis",
            "product": "Nike Air Force 1 Low '07 LV8 - Supreme Black",
			"description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
			"price": 94.50,
			"stock": 15,
		},
		{
            "id": 4,
			"image": "https://images.stockx.com/360/Nike-Air-Force-1-Low-Triple-Red/Images/Nike-Air-Force-1-Low-Triple-Red/Lv2/img01.jpg?fm=avif&auto=compress&w=480&dpr=2&updated_at=1635190633&h=320&q=75",
			"category": "tenis",
            "product": "Nike Air Force 1 Low - Triple Red",
			"description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
			"price": 438.90,
			"stock": 5
		},
		{
			"id": 8,
			"image": "https://images.stockx.com/images/Nike-Air-Force-1-07-Low-Color-of-the-Month-University-Red-Gum.jpg?fit=fill&bg=FFFFFF&w=480&h=320&fm=avif&auto=compress&dpr=3&trim=color&updated_at=1659374579&q=50",
			"product": "Nike Air Force 1 '07 Low - Color of the Month University Red Gum",
            "category": "tenis",
			"description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
			"price": 94.50,
			"stock": 15,
		},
		{
            "id": 6,
			"image": "https://images.stockx.com/360/Nike-Air-Force-1-Low-07-University-Blue-White/Images/Nike-Air-Force-1-Low-07-University-Blue-White/Lv2/img01.jpg?fm=avif&auto=compress&w=480&dpr=1&updated_at=1637619107&h=320&q=80",
            "product": "Nike Air Force 1 Low - University Blue White",
			"category": "tenis",
			"description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
			"price": 163,
			"stock": 100,
		},
		{
            "id": 7,
			"image": "https://images.stockx.com/images/Nike-Air-Force-1-Low-07-Worldwide-Pack-Blue-Fury-PS.jpg?fit=fill&bg=FFFFFF&w=480&h=320&fm=avif&auto=compress&dpr=2&trim=color&updated_at=1644276222&q=75",
			"product": "NIKE AIR FORCE 1 SNEAKERS",
            "category": "tenis",
			"description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
			"price": 91,
			"stock": 2,
		},
		{
            "id": 5,
			"image": "https://images.stockx.com/360/Nike-Air-Force-1-Low-White-University-Gold/Images/Nike-Air-Force-1-Low-White-University-Gold/Lv2/img01.jpg?fm=avif&auto=compress&w=480&dpr=1&updated_at=1635346750&h=320&q=80",
			"category": "tenis",
            "product": "Nike Air Force 1 Low - White University Blue (GS)",
			"description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
			"price": 20,
			"stock": 3,
		},
		{
            "id": 9,
			"image": "https://images.stockx.com/images/Nike-Air-Force-1-07-LV8-Blue-Worldwide-Thumb.png?fit=fill&bg=FFFFFF&w=480&h=320&fm=avif&auto=compress&dpr=2&trim=color&updated_at=1607668814&q=75",
            "category": "tenis",
            "product": "Nike Air Force 1 Low '07 LV8 - Worldwide Pack White Blue Fury",
			"description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
			"price": 438.90,
			"stock": 5
		},
		{
            "id": 10,
			"image": "https://images.stockx.com/360/Nike-Air-Force-1-Low-White-University-Blue-GS/Images/Nike-Air-Force-1-Low-White-University-Blue-GS/Lv2/img01.jpg?fm=avif&auto=compress&w=480&dpr=2&updated_at=1626904155&h=320&q=75",
            "product": "Nike Air Force 1 Low - White University Blue (GS)",
            "category": "tenis",
			"description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
			"price": 20,
			"stock": 3,
		},
		{
            "id": 11,
			"image": "https://images.stockx.com/images/Nike-Air-Force-1-Low-07-Worldwide-Pack-Blue-Fury-PS.jpg?fit=fill&bg=FFFFFF&w=480&h=320&fm=avif&auto=compress&dpr=2&trim=color&updated_at=1644276222&q=75",
			"product": "NIKE AIR FORCE 1 SNEAKERS",
            "category": "tenis",
			"description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
			"price": 110,
			"stock": 100,
		},
		{
            "id": 12,
			"image": "https://images.stockx.com/images/Nike-Air-Force-1-Low-07-Worldwide-Pack-Blue-Fury-PS.jpg?fit=fill&bg=FFFFFF&w=480&h=320&fm=avif&auto=compress&dpr=2&trim=color&updated_at=1644276222&q=75",
			"product": "NIKE AIR FORCE 1 SNEAKERS",
            "category": "tenis",
			"description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
			"price": 91,
			"stock": 2,
		},
		{
            "id": 13,
			"image": "https://guesseu.scene7.com/is/image/GuessEU/HWVG6216060-TAN?wid=700&amp;fmt=jpeg&amp;qlt=80&amp;op_sharpen=0&amp;op_usm=1.0,1.0,5,0&amp;iccEmbed=0",
			"category": "bolsos",
            "product": "CATE RIGID BAG",
			"description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
			"price": 94.50,
			"stock": 15,
		},
		{
            "id": 14,
			"image": "http://guesseu.scene7.com/is/image/GuessEU/WC0001FMSWC-G5?wid=520&fmt=jpeg&qlt=80&op_sharpen=0&op_usm=1.0,1.0,5,0&iccEmbed=0",
			"category": "relojes",
            "product": "GUESS CONNECT WATCH",
			"description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
			"price": 438.90,
			"stock": 5
		},
		{
            "id": 15,
			"image": "https://guesseu.scene7.com/is/image/GuessEU/AW6308VIS03-SAP?wid=700&amp;fmt=jpeg&amp;qlt=80&amp;op_sharpen=0&amp;op_usm=1.0,1.0,5,0&amp;iccEmbed=0",
			"category": "bufandas",
            "product": "'70s RETRO GLAM KEFIAH",
			"description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
			"price": 20,
			"stock": 3,
		}
]
