export const products = [
		{
			"id": 1,
			"image": "https://images.stockx.com/360/Nike-Air-Force-1-Low-Supreme-Box-Logo-White/Images/Nike-Air-Force-1-Low-Supreme-Box-Logo-White/Lv2/img01.jpg?fm=avif&auto=compress&w=480&dpr=3&updated_at=1635187755&h=320&q=50",
			"product": "NIKE AIR FORCE 1 - Supreme White",
			"color": "Supreme White",
			"description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
            "category": "tenis",
			"price": 320,
			"stock": 2,
		},
		{
            "id": 2,
			"image": "https://images.stockx.com/360/Nike-Air-Force-1-Low-Flax-2019/Images/Nike-Air-Force-1-Low-Flax-2019/Lv2/img01.jpg?fm=avif&auto=compress&w=480&dpr=3&updated_at=1635252806&h=320&q=50",
			"product": "NIKE AIR FORCE 1 - Flax (2019/2022)			",
			"color": "DUNE",
			"description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
            "category": "tenis",
			"price": 450,
			"stock": 100,
		},
		{
            "id": 3,
			"image": "https://images.stockx.com/360/Nike-Air-Force-1-Low-Supreme-Box-Logo-Black/Images/Nike-Air-Force-1-Low-Supreme-Box-Logo-Black/Lv2/img01.jpg?fm=avif&auto=compress&w=480&dpr=2&updated_at=1635277631&h=320&q=75",
            "category": "tenis",
			"color": "Supreme Black",
            "product": "Nike Air Force 1 Low '07 LV8 - Supreme Black",
			"description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
			"price": 220,
			"stock": 15,
		},
		{
            "id": 4,
			"image": "https://images.stockx.com/images/Nike-Air-Force-1-Low-07-Coconut-Milk-Rattan.jpg?fit=fill&bg=FFFFFF&w=480&h=320&fm=avif&auto=compress&dpr=2&trim=color&updated_at=1657828464&q=75",
			"category": "tenis",
			"color": "Coconut Milk Rattan",
            "product": "Nike Air Force 1 Low - Coconut Milk Rattan			",
			"description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
			"price": 199,
			"stock": 5
		},
		{
			"id": 5,
			"image": "https://images.stockx.com/images/Nike-Air-Force-1-07-Low-Color-of-the-Month-University-Red-Gum.jpg?fit=fill&bg=FFFFFF&w=480&h=320&fm=avif&auto=compress&dpr=3&trim=color&updated_at=1659374579&q=50",
			"product": "Nike Air Force 1 '07 Low - Color of the Month University Red Gum",
			"color": "Red Gum",
            "category": "tenis",
			"description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
			"price": 110,
			"stock": 15,
		},
		{
            "id": 6,
			"image": "https://images.stockx.com/images/Nike-Air-Force-1-Low-07-White-Rattan.jpg?fit=fill&bg=FFFFFF&w=480&h=320&fm=avif&auto=compress&dpr=4&trim=color&updated_at=1657828466&q=45",
            "product": "Nike Air Force 1 Low - White Rattan			",
			"category": "tenis",
			"color": "White Rattan	",
			"description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
			"price": 250,
			"stock": 100,
		},
		{
            "id": 7,
			"image": "https://images.stockx.com/images/Nike-Air-Force-1-Low-07-LV8-Certified-Fresh-Rattan.jpg?fit=fill&bg=FFFFFF&w=480&h=320&fm=avif&auto=compress&dpr=4&trim=color&updated_at=1659374579&q=45",
            "product": "Nike Air Force 1 Low - Certified Fresh Rattan",
            "category": "tenis",
			"color": "Fresh Rattan	",
			"description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
			"price": 450,
			"stock": 2,
		},
		{
            "id": 8,
			"image": "https://images.stockx.com/360/Nike-Air-Force-1-Low-Stussy-Fossil/Images/Nike-Air-Force-1-Low-Stussy-Fossil/Lv2/img01.jpg?fm=avif&auto=compress&w=480&dpr=1&updated_at=1635276714&h=320&q=80",
			"category": "tenis",
            "product": "Nike Air Force 1 Low - Stussy Fossil			",
			"color": "Stussy Fossil	",
			"description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
			"price": 349,
			"stock": 3,
		},
		{
            "id": 9,
			"image": "https://images.stockx.com/images/Nike-Air-Force-1-Low-Black-Gum-W.png?fit=fill&bg=FFFFFF&w=480&h=320&fm=avif&auto=compress&dpr=1&trim=color&updated_at=1608518521&q=80",
            "category": "tenis",
            "product": "Nike Air Force 1 Low '07 LV8 - Black Gum (W)			",
			"color": "Black Gum (W)	",
			"description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
			"price": 438.90,
			"stock": 5
		},
		{
            "id": 10,
			"image": "https://images.stockx.com/360/Nike-Air-Force-1-Low-07-Black-White/Images/Nike-Air-Force-1-Low-07-Black-White/Lv2/img01.jpg?fm=avif&auto=compress&w=480&dpr=1&updated_at=1635539968&h=320&q=80",
			"color": "Black	",
            "category": "tenis",
			"product": "Nike Air Force 1 Low '07 LV8 - Black			",
			"description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
			"price": 20,
			"stock": 3,
		},
		{
            "id": 11,
			"image": "https://images.stockx.com/images/Fear-of-God-Essentials-SSENSE-Exclusive-Pullover-Hoodie-Linen.jpg?fit=fill&bg=FFFFFF&w=480&h=320&fm=avif&auto=compress&dpr=2&trim=color&updated_at=1638383116&q=75",
			"product": "Fear of God Essentials SSENSE Exclusive Pullover Hoodie			",
            "category": "apparel", 
			"color": "Beish God	",
			"description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
			"price": 110,
			"stock": 100,
		},
		{
            "id": 12,
			"image": "https://images.stockx.com/images/Fear-of-God-Essentials-T-shirt-Desert-Taupe.jpg?fit=fill&bg=FFFFFF&w=480&h=320&fm=avif&auto=compress&dpr=2&trim=color&updated_at=1651183268&q=75",
			"product": "Fear of God Essentials T-shirt - COLOR DESERT TAUPE			",
            "category": "apparel", 
			"color": "Desert	",
			"description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
			"price": 80,
			"stock": 2,
		},
		{
            "id": 13,
			"image": "https://images.stockx.com/images/Yeezy-Bouclette-Socks-3-Pack-Color-Two.png?fit=fill&bg=FFFFFF&w=480&h=320&fm=avif&auto=compress&dpr=2&trim=color&updated_at=1618973431&q=75",
			"category": "apparel",
			"color": "Dune	",
            "product": "Yeezy Bouclette Socks (3 Pack) - COLOR DUNE		",
			"description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
			"price": 50,
			"stock": 15,
		},
		{
            "id": 14,
			"image": "https://images.stockx.com/images/FEAR-OF-GOD-ESSENTIALS-T-shirt-Moss-Goat.jpg?fit=fill&bg=FFFFFF&w=480&h=320&fm=avif&auto=compress&dpr=1&trim=color&updated_at=1620861744&q=80",
			"category": "apparel",
			"color": "Moss	",
            "product": "Fear of God Essentials T-shirt - COLOR MOSS/GOAT			",
			"description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
			"price": 30,
			"stock": 5
		},
		{
            "id": 15,
			"image": "https://images.stockx.com/images/OVO-Essentials-T-Shirt-White.jpg?fit=fill&bg=FFFFFF&w=480&h=320&fm=avif&auto=compress&dpr=4&trim=color&updated_at=1622227849&q=45",
			"category": "apparel",
			"color": "White	",
            "product": "FOVO Essentials T-shirt			",
			"description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
			"price": 91,
			"stock": 5
		},
		{
            "id": 16,
			"image": "https://images.stockx.com/images/Beats-x-Kim-K-Fit-Pro-True-Wireless-Earbuds-Special-Edition-MNW63LL-A-Dune.jpg?fit=fill&bg=FFFFFF&w=480&h=320&fm=avif&auto=compress&dpr=2&trim=color&updated_at=1660318575&q=75",
			"category": "electronics",
			"color": "Dune	",
            "product": "Beats x Kim K Fit Pro True Wireless Earbuds Special Edition MNW63LL/A - COLOR DUNE		",
			"description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
			"price": 245,
			"stock": 3,
		},
		{
            "id": 17,
			"image": "https://images.stockx.com/images/Beats-x-Kim-K-Fit-Pro-True-Wireless-Earbuds-Special-Edition-MNW63LL-A-Moon.jpg?fit=fill&bg=FFFFFF&w=480&h=320&fm=avif&auto=compress&dpr=2&trim=color&updated_at=1660318573&q=75",
			"category": "electronics",
			"color": "Moon	",
            "product": "Beats x Kim K Fit Pro True Wireless Earbuds Special Edition MNW63LL/A - COLOR MOON		",
			"description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
			"price": 230,
			"stock": 18,
		},
		{
            "id": 18,
			"image": "https://images.stockx.com/images/Beats-x-Kim-K-Fit-Pro-True-Wireless-Earbuds-Special-Edition-MNW63LL-A-Earth.jpg?fit=fill&bg=FFFFFF&w=480&h=320&fm=avif&auto=compress&dpr=4&trim=color&updated_at=1660318575&q=45",
			"category": "electronics",
			"color": "Earth	",
            "product": "Beats x Kim K Fit Pro True Wireless Earbuds Special Edition MNW63LL/A - COLOR EARTH		",
			"description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
			"price": 230,
			"stock": 20,
		},
		{
            "id": 19,
			"image": "https://images.stockx.com/images/Beats-Studio3-Wireless-Headphones-Shadow-Gray.jpg?fit=fill&bg=FFFFFF&w=480&h=320&fm=avif&auto=compress&dpr=2&trim=color&updated_at=1607374259&q=75",
			"category": "electronics",
			"color": "Shadow grey",
            "product": "Beats Studio3 Wireless Headphones MXJ92LL/A - COLOR SHADOW GREY			",
			"description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
			"price": 350,
			"stock": 2,
		},
		{
            "id": 20,
			"image": "https://images.stockx.com/images/Beats-Studio3-Wireless-Headphones-MX3X2LL-A-Matte-Black.jpg?fit=fill&bg=FFFFFF&w=480&h=320&fm=avif&auto=compress&dpr=1&trim=color&updated_at=1607374252&q=80",
			"category": "electronics",
			"color": "Matter Black",
            "product": "Beats Studio3 Wireless Headphones MX3X2LL/A		- COLOR MATTER BLACK	",
			"description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
			"price": 200,
			"stock": 1,
		},
		{
            "id": 21,
			"image": "https://images.stockx.com/images/Beats-Studio3-Wireless-Headphones-White.jpg?fit=fill&bg=FFFFFF&w=480&h=320&fm=avif&auto=compress&dpr=1&trim=color&updated_at=1607374261&q=80",
			"category": "electronics",
			"color": "White",
            "product": "Beats Studio3 Wireless Headphones (MQ572LL/A&MX3Y2LL/A)			- COLOR WHITE		",
			"description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
			"price": 249,
			"stock": 20,
		},
		{
            "id": 22,
			"image": "https://images.stockx.com/360/adidas-Yeezy-Slide-Bone-2022/Images/adidas-Yeezy-Slide-Bone-2022/Lv2/img01.jpg?fm=avif&auto=compress&w=480&dpr=1&updated_at=1660144762&h=320&q=80",
			"category": "sandals",
			"color": "Bone",
            "product": "adidas Yeezy Slide			- COLOR Bone (2022 Restock)			",
			"description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
			"price": 180,
			"stock": 20,
		},
		{
            "id": 23,
			"image": "https://images.stockx.com/360/Yeezy-Slide-Bone/Images/Yeezy-Slide-Bone/Lv2/img01.jpg?fm=avif&auto=compress&w=480&dpr=2&updated_at=1635191602&h=320&q=75",
			"category": "sandals",
			"color": "Dune",
            "product": "adidas Yeezy Slide			- COLOR dune (2022 Restock)			",
			"description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
			"price": 249,
			"stock": 20,
		},
		{
            "id": 24,
			"image": "https://images.stockx.com/360/adidas-Yeezy-Slide-Black/Images/adidas-Yeezy-Slide-Black/Lv2/img01.jpg?fm=avif&auto=compress&w=480&dpr=1&updated_at=1646687558&h=320&q=80",
			"category": "sandals",
			"color": "Onyx",
            "product": "adidas Yeezy Slide			- COLOR Onyx			",
			"description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
			"price": 249,
			"stock": 20,
		}
]
