export const products = [
		{
            "id": 1,
			"image": "https://guesseu.scene7.com/is/image/GuessEU/M63H24W7JF0-L302-ALTGHOST?wid=1500&fmt=jpeg&qlt=80&op_sharpen=0&op_usm=1.0,1.0,5,0&iccEmbed=0",
			"product": "CHECK PRINT SHIRT",
            "category": "camisas",
			"price": 110,
			"stock": 100,
		},
		{
            "id": 2,
			"image": "https://guesseu.scene7.com/is/image/GuessEU/FLGLO4FAL12-BEIBR?wid=700&amp;fmt=jpeg&amp;qlt=80&amp;op_sharpen=0&amp;op_usm=1.0,1.0,5,0&amp;iccEmbed=0",
			"product": "GLORIA HIGH LOGO SNEAKER",
            "category": "tenis",
			"price": 91,
			"stock": 2,
		},
		{
            "id": 3,
			"image": "https://guesseu.scene7.com/is/image/GuessEU/HWVG6216060-TAN?wid=700&amp;fmt=jpeg&amp;qlt=80&amp;op_sharpen=0&amp;op_usm=1.0,1.0,5,0&amp;iccEmbed=0",
			"category": "bolsos",
            "product": "CATE RIGID BAG",
			"price": 94.50,
			"stock": 15,
		},
		{
            "id": 4,
			"image": "http://guesseu.scene7.com/is/image/GuessEU/WC0001FMSWC-G5?wid=520&fmt=jpeg&qlt=80&op_sharpen=0&op_usm=1.0,1.0,5,0&iccEmbed=0",
			"category": "relojes",
            "product": "GUESS CONNECT WATCH",
			"price": 438.90,
			"stock": 5
		},
		{
            "id": 5,
			"image": "https://guesseu.scene7.com/is/image/GuessEU/AW6308VIS03-SAP?wid=700&amp;fmt=jpeg&amp;qlt=80&amp;op_sharpen=0&amp;op_usm=1.0,1.0,5,0&amp;iccEmbed=0",
			"category": "bufandas",
            "product": "'70s RETRO GLAM KEFIAH",
			"price": 20,
			"stock": 3,
		},
		{
            "id": 6,
			"image": "https://guesseu.scene7.com/is/image/GuessEU/M63H24W7JF0-L302-ALTGHOST?wid=1500&fmt=jpeg&qlt=80&op_sharpen=0&op_usm=1.0,1.0,5,0&iccEmbed=0",
			"product": "CHECK PRINT SHIRT",
            "category": "camisas",
			"price": 110,
			"stock": 100,
		},
		{
            "id": 7,
			"image": "https://guesseu.scene7.com/is/image/GuessEU/FLGLO4FAL12-BEIBR?wid=700&amp;fmt=jpeg&amp;qlt=80&amp;op_sharpen=0&amp;op_usm=1.0,1.0,5,0&amp;iccEmbed=0",
			"product": "GLORIA HIGH LOGO SNEAKER",
            "category": "tenis",
			"price": 91,
			"stock": 2,
		},
		{
            "id": 8,
			"image": "https://guesseu.scene7.com/is/image/GuessEU/HWVG6216060-TAN?wid=700&amp;fmt=jpeg&amp;qlt=80&amp;op_sharpen=0&amp;op_usm=1.0,1.0,5,0&amp;iccEmbed=0",
			"category": "bolsos",
            "product": "CATE RIGID BAG",
			"price": 94.50,
			"stock": 15,
		},
		{
            "id": 9,
			"image": "http://guesseu.scene7.com/is/image/GuessEU/WC0001FMSWC-G5?wid=520&fmt=jpeg&qlt=80&op_sharpen=0&op_usm=1.0,1.0,5,0&iccEmbed=0",
			"category": "relojes",
            "product": "GUESS CONNECT WATCH",
			"price": 438.90,
			"stock": 5
		},
		{
            "id": 10,
			"image": "https://guesseu.scene7.com/is/image/GuessEU/AW6308VIS03-SAP?wid=700&amp;fmt=jpeg&amp;qlt=80&amp;op_sharpen=0&amp;op_usm=1.0,1.0,5,0&amp;iccEmbed=0",
			"category": "bufandas",
            "product": "'70s RETRO GLAM KEFIAH",
			"price": 20,
			"stock": 3,
		},
		{
            "id": 11,
			"image": "https://guesseu.scene7.com/is/image/GuessEU/M63H24W7JF0-L302-ALTGHOST?wid=1500&fmt=jpeg&qlt=80&op_sharpen=0&op_usm=1.0,1.0,5,0&iccEmbed=0",
			"product": "CHECK PRINT SHIRT",
            "category": "camisas",
			"price": 110,
			"stock": 100,
		},
		{
            "id": 12,
			"image": "https://guesseu.scene7.com/is/image/GuessEU/FLGLO4FAL12-BEIBR?wid=700&amp;fmt=jpeg&amp;qlt=80&amp;op_sharpen=0&amp;op_usm=1.0,1.0,5,0&amp;iccEmbed=0",
			"product": "GLORIA HIGH LOGO SNEAKER",
            "category": "tenis",
			"price": 91,
			"stock": 2,
		},
		{
            "id": 13,
			"image": "https://guesseu.scene7.com/is/image/GuessEU/HWVG6216060-TAN?wid=700&amp;fmt=jpeg&amp;qlt=80&amp;op_sharpen=0&amp;op_usm=1.0,1.0,5,0&amp;iccEmbed=0",
			"category": "bolsos",
            "product": "CATE RIGID BAG",
			"price": 94.50,
			"stock": 15,
		},
		{
            "id": 14,
			"image": "http://guesseu.scene7.com/is/image/GuessEU/WC0001FMSWC-G5?wid=520&fmt=jpeg&qlt=80&op_sharpen=0&op_usm=1.0,1.0,5,0&iccEmbed=0",
			"category": "relojes",
            "product": "GUESS CONNECT WATCH",
			"price": 438.90,
			"stock": 5
		},
		{
            "id": 15,
			"image": "https://guesseu.scene7.com/is/image/GuessEU/AW6308VIS03-SAP?wid=700&amp;fmt=jpeg&amp;qlt=80&amp;op_sharpen=0&amp;op_usm=1.0,1.0,5,0&amp;iccEmbed=0",
			"category": "bufandas",
            "product": "'70s RETRO GLAM KEFIAH",
			"price": 20,
			"stock": 3,
		}
]
